# action.yml
name: 'Typo checking'
description: 'Just test if it works'
inputs:
  list-files:
    description: 'List of changed file'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.list-files }}
